DROP TABLE USERS;	

CREATE TABLE COMM001
(
	CODE	VARCHAR2(4)	NOT NULL,
	CONTENT	VARCHAR2(20)	NOT NULL,
	
	CONSTRAINT COMM_PK PRIMARY KEY (CODE)
);

CREATE TABLE USERS 
(	    
	USER_NO		NUMBER(10)		NOT NULL, -- 회원고유번호
    USER_ID 	VARCHAR2(50) 	NOT NULL, -- 아이디
    USER_PW 	VARCHAR2(6) 	NOT NULL, -- 비밀번호
    USER_NAME 	VARCHAR2(20) 	NOT NULL, -- 이름
    SEX 		CHAR(1) 		NOT NULL, -- 성별
    BIRTH 		VARCHAR2(10) 	NOT NULL, -- 생년월일
    EMAIL 		VARCHAR2(20) 	NOT NULL, -- 이메일
    PHONE_NO 	VARCHAR2(20) 	NOT NULL, -- 핸드폰번호
    USER_ZCODE 	VARCHAR2(20) 	NOT NULL, -- 우편번호?
    ADDR1 		VARCHAR2(50) 	NOT NULL, -- 주소상세1 API 확인 필요
    ADDR2 		VARCHAR2(50) 	NOT NULL, -- 주소상세2
    CREATEDATE 	DATE 			NOT NULL, -- 가입날짜
    UPDATEDATE 	DATE 			, 		  -- 업데이트 날짜? 
    LASTLOGIN   DATE 			NOT NULL, -- 마지막 접속 날짜
    USER_USE 	CHAR(1) 		NOT NULL, -- 아이디 사용 여부
    CART		VARCHAR2(50)	, 		  -- 장바구니
    CODE		VARCHAR2(4)		NOT NULL, -- 권한
    
  	CONSTRAINT USER_PK PRIMARY KEY (USER_NO,USER_ID),
  	CONSTRAINT ROLE_CODE FOREIGN KEY(CODE) REFERENCES COMM001(CODE)
); 
	
COMMENT ON COLUMN USERS.USER_NO 	IS '회원고유번호';
COMMENT ON COLUMN USERS.USER_ID 	IS '아이디';
COMMENT ON COLUMN USERS.USER_PW 	IS '비밀번호';
COMMENT ON COLUMN USERS.SEX 		IS '성별';
COMMENT ON COLUMN USERS.BIRTH 		IS '생년월일';
COMMENT ON COLUMN USERS.EMAIL 		IS '이메일';
COMMENT ON COLUMN USERS.PHONE_NO 	IS '핸드폰번호';
COMMENT ON COLUMN USERS.USER_ZCODE 	IS '';
COMMENT ON COLUMN USERS.ADDR1 		IS '';
COMMENT ON COLUMN USERS.ADDR2 		IS '';
COMMENT ON COLUMN USERS.CREATEDATE 	IS '가입날짜';
COMMENT ON COLUMN USERS.UPDATEDATE 	IS '업데이트날짜';
COMMENT ON COLUMN USERS.LASTLOGIN 	IS '마지막접속날짜';
COMMENT ON COLUMN USERS.USER_USE 	IS '아이디사용여부';
COMMENT ON COLUMN USERS.CART 		IS '장바구니';
COMMENT ON COLUMN USERS.CODE 		IS '권한';
	
  
CREATE TABLE PRODUCTS
(
	PRODUCT_NO		NUMBER(10)		NOT NULL, --상품고유번호
	PRODUCT_ID		VARCHAR2(20)	NOT NULL, --상품아이디
	BRAND_NO		VARCHAR2(3)		NOT NULL, --브랜드고유번호
	PRODUCT_TYPE	VARCHAR2(3)		NOT NULL, --타입
	CONTENT			VARCHAR2(200)	NOT NULL, --설명
	IMAGES			VARCHAR2()		NOT NULL, --이미지
	PRICE			VARCHAR2()		NOT NULL, --가격
	STOCK			NUMBER(10)		NOT NULL, --재고
	IMAGES			VARCHAR2()		NOT NULL, --상품이미지
	IMAGES			VARCHAR2()		NOT NULL, --상품이미지
);
COMMIT;